### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by IlanFrumer** [TheVelourFog/slush-angular2#3]
``` shell
> slush angular2
[slush] Using slushfile /usr/local/lib/node_modules/slush-angular2/slushfile.js
[16:07:40] Starting 'angular2:default'...
? Name Your App: test
[16:07:43] [conflict] Creating README.md
[16:07:43] [conflict] Creating gulpfile.js
[16:07:43] [conflict] Creating package.json
[16:07:43] [conflict] Creating src
[16:07:43] [conflict] Creating tsconfig.json
[16:07:43] [conflict] Creating tsd.json
[16:07:43] [conflict] Creating src/content
[16:07:43] [conflict] Creating src/index.html
[16:07:43] [conflict] Creating src/ts
[16:07:43] [conflict] Creating src/typings
[16:07:43] [conflict] Creating src/content/angular-material-layout.css
[16:07:43] [conflict] Creating src/content/browserconfig.xml
[16:07:43] [conflict] Creating src/content/favicon.ico
[16:07:43] [conflict] Creating src/content/humans.txt
[16:07:43] [conflict] Creating src/content/manifest.json
[16:07:43] [conflict] Creating src/content/robots.txt
[16:07:43] [conflict] Creating src/content/shield.svg
[16:07:43] [conflict] Creating src/ts/example.ts
[16:07:43] [conflict] Creating src/ts/index.ts
[16:07:43] [conflict] Creating src/typings/angular2
[16:07:43] [conflict] Creating src/typings/es6-promise
[16:07:43] [conflict] Creating src/typings/rx
[16:07:43] [conflict] Creating src/typings/tsd.d.ts

events.js:85
      throw er; // Unhandled 'error' event
            ^
ReferenceError: value is not defined
    at eval (lodash.templateSources[16]:9:10)
    at DestroyableTransform._transform (/usr/local/lib/node_modules/slush-angular2/node_modules/gulp-template/index.js:21:40)
    at DestroyableTransform.Transform._read (/usr/local/lib/node_modules/slush-angular2/node_modules/gulp-template/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/usr/local/lib/node_modules/slush-angular2/node_modules/gulp-template/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/usr/local/lib/node_modules/slush-angular2/node_modules/gulp-template/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/usr/local/lib/node_modules/slush-angular2/node_modules/gulp-template/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/usr/local/lib/node_modules/slush-angular2/node_modules/gulp-template/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/usr/local/lib/node_modules/slush-angular2/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/usr/local/lib/node_modules/slush-angular2/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/usr/local/lib/node_modules/slush-angular2/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
```

**Comment by RyanMetin** [comment]
Thanks for letting me know. I'm on vacation, but I'll fix it as soon as I can.

**Comment by Shamballa** [comment]
This application really worked great, but now I got the same error as IlanFrumer. Is there any solution so far?

**Comment by RyanMetin** [comment]
Yes! Thank you for reminding me, actually. I'll publish this evening.
