### ISSUE TITLE
Creation of the project fails

### ISSUE THREAD

**Issue by fedy2** [TheVelourFog/slush-angular2#6]
I don't know if it is related to slush-angular2 package but the creation of a new project fails.
I'm pasting the relevant part of the console log:

``` bash
lavoro@guendalinaXIII ~/projects/angular2prj $ slush angular2
[slush] Using slushfile /home/lavoro/.node/lib/node_modules/slush-angular2/slushfile.js
[08:19:01] Starting 'angular2:default'...
? Name your project: slushy
? Everything look good? Yes
[08:19:11] [conflict] Creating README.md
[08:19:11] [conflict] Creating .editorconfig
[08:19:11] [conflict] Creating config.js
[08:19:11] [conflict] Creating gulpfile.js
[08:19:11] [conflict] Creating index.html
[08:19:11] [conflict] Creating package.json
[08:19:11] [conflict] Creating src
[08:19:11] [conflict] Creating tsconfig.json
[08:19:11] [conflict] Creating tsd.json
[08:19:11] [conflict] Creating src/boot.ts
[08:19:11] [conflict] Creating src/example.ts
[08:19:11] Finished 'angular2:default' after 9.78 s
[slush] Scaffolding done
npm WARN package.json slushy@0.0.1 No repository field.
npm WARN package.json slushy@0.0.1 No license field.
|
-> running reinstall
/
>> written zero files
npm WARN engine joi-assert@0.0.3: wanted: {"node":">= 0.10.0 <= 0.11.0"} (current: {"node":"0.12.7","npm":"2.11.3"})
-
> slushy@0.0.1 postinstall /home/lavoro/projects/angular2prj/slushy
> jspm install && tsd install angular2 es6-promise rx rx-lite systemjs -ros

```

... install logs ...

``` bash
ok   Installed angular2 as npm:angular2@^2.0.0-alpha.36 (2.0.0-alpha.36)
     Installed Forks

                                   npm:rx 2.5.1 3.0.0

     To inspect individual package constraints, use jspm inspect registry:name.


warn typescript@1.5.3 is unsupported for this version of jspm. Use jspm dl-loader to update.
     Looking up loader files...
       system.js
       system.src.js
       system.js.map
       system-csp-production.js
       system-csp-production.src.js
       system-csp-production.js.map
       system-polyfills.js
       system-polyfills.src.js
       system-polyfills.js.map

     Using loader versions:
       systemjs@0.18.17
ok   Loader files downloaded successfully

ok   Install complete.
[ERR!] cwd  : /home/lavoro/projects/angular2prj/slushy
[ERR!] os   : Linux 3.13.0-24-generic
[ERR!] argv : "node" "/home/lavoro/projects/angular2prj/slushy/node_modules/.bin/tsd" "install" "angular2" "es6-promise" "rx" "rx-lite" "systemjs" "-ros"
[ERR!] node : v0.12.7
[ERR!] tsd  : 0.6.4
[ERR!] Error: path exists but is not a directory /home/lavoro/.tsd-cache/borisyankov-DefinitelyTyped/git-raw-fmt1.0/82
[ERR!] CODE : undefined
[ERR!] path exists but is not a directory /home/lavoro/.tsd-cache/borisyankov-DefinitelyTyped/git-raw-fmt1.0/82
[ERR!] If you need help, you may report this error at:
    https://github.com/DefinitelyTyped/tsd/issues

[ERR!] .tsdrc could not be retrieved

[ERR!] Please include the following file with any support request:
    /home/lavoro/projects/angular2prj/slushy/tsd-debug.log


npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! slushy@0.0.1 postinstall: `jspm install && tsd install angular2 es6-promise rx rx-lite systemjs -ros`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the slushy@0.0.1 postinstall script 'jspm install && tsd install angular2 es6-promise rx rx-lite systemjs -ros'.
npm ERR! This is most likely a problem with the slushy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     jspm install && tsd install angular2 es6-promise rx rx-lite systemjs -ros
npm ERR! You can get their info via:
npm ERR!     npm owner ls slushy
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/lavoro/projects/angular2prj/slushy/npm-debug.log
[08:20:54] npm exited with non-zero code 1 , run `npm install` manually
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: npm exited with non-zero code 1
    at ChildProcess.<anonymous> (/home/lavoro/.node/lib/node_modules/slush-angular2/node_modules/gulp-install/lib/commandRunner.js:14:19)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
```

**Comment by RyanMetin** [comment]
It looks like a problem with _tsd_. See if there's an error code in the `tsd-debug.log`, or post it here.
